// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/article.vue')['default']
    Bg: typeof import('./src/components/index/bg.vue')['default']
    Button_1: typeof import('./src/components/index/button_1.vue')['default']
    Button_2: typeof import('./src/components/index/button_2.vue')['default']
    Button_confirm: typeof import('./src/components/index/button_confirm.vue')['default']
    Components: typeof import('./src/components/index.vue')['default']
    DeathClock: typeof import('./src/components/index/deathClock.vue')['default']
    LiveClock: typeof import('./src/components/index/liveClock.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    Me: typeof import('./src/components/me.vue')['default']
    Planning: typeof import('./src/components/planning/planning.vue')['default']
    PlayControl: typeof import('./src/components/playControl/index.vue')['default']
    Popup: typeof import('./src/components/index/popup.vue')['default']
    Repetitive: typeof import('./src/components/playControl/Repetitive.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shop: typeof import('./src/components/shop.vue')['default']
    Timer: typeof import('./src/components/index/timer.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    TodoItem: typeof import('./src/components/planning/todoItem.vue')['default']
    TodoList: typeof import('./src/components/planning/todoList.vue')['default']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanButton: typeof import('vant/es')['Button']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCircle: typeof import('vant/es')['Circle']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanIcon: typeof import('vant/es')['Icon']
    VanImagePreview: typeof import('vant/es')['ImagePreview']
    VanLoading: typeof import('vant/es')['Loading']
    VanPicker: typeof import('vant/es')['Picker']
    VanPickerGroup: typeof import('vant/es')['PickerGroup']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanSlider: typeof import('vant/es')['Slider']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTimePicker: typeof import('vant/es')['TimePicker']
    VanToast: typeof import('vant/es')['Toast']
  }
}
